version: '3.1'
networks:
  my-network:
    driver: bridge
services:
  web-nginx:
    image: 'nginx:alpine'
    container_name: web-nginx
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    links:
      - php-fpm
  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overides.ini